### ISSUE TITLE
Add automatically documentation with phpDocument

### ISSUE THREAD

**Issue by wppunk** [wppunk/WPPlugin#15]
**Is your feature request related to a problem? Please describe.**

Automatically create documentation for WordPress hooks in PHP code. To generate it you can use https://github.com/phpDocumentor/phpDocumentor. To generate it inside the GH Actions:
```
- name: PhpDocumentor
        uses: gpupo/actions-phpDocumentor@1.0
        with:
          dir: './'
```
